# Generated by Django 5.0.6 on 2024-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='max_slots',
        ),
        migrations.AddField(
            model_name='resource',
            name='max_duration',
            field=models.IntegerField(default=4),
        ),
    ]
